# Generated by Django 5.0 on 2023-12-21 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_category_quizmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryModel',
        ),
    ]
