# Generated by Django 5.0 on 2023-12-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_alter_registermodel_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='profile_img',
            field=models.ImageField(blank=True, default='profile_images/userprofile.png', null=True, upload_to='profile_images'),
        ),
    ]
